astra/ui/element/widget/block.cpp File Reference
#include "block.h"
#include <algorithm>
#include <hal/hal.h>
Functions
void applyRotation (const float rotationMatrix[3][3], float points[8][3])
Function Documentation
applyRotation()
void applyRotation (const float rotationMatrix[3][3], float points[8][3])
Definition at line 13 of file block.cpp.
Referenced by block::rotateX(), block::rotateY(), and block::rotateZ().