astra::ui::Camera Class Reference
#include <Camera.h>
Public Member Functions
uint8_t outOfView (float _x, float _y) const
std::vector< float > getPosition () const
void go (float _x, float _y)
void goDirect (float _x, float _y)
void goHorizontal (float _x)
void goVertical (float _y)
void goToNextPageItem ()
void goToPreviewPageItem ()
void goToListItemPage (uint8_t _index)
void goToListItemRolling (const std::vector< float > &_posSelector)
void goToTileItem (uint8_t _index)
bool isMoving () const
void reset ()
void update (Menu *_menu, Selector *_selector)
virtual void entryAnimation ()
virtual void exitAnimation ()
virtual void blur ()
virtual void animation (float *_pos, float _posTrg, float _speed)
Static Public Member Functions
static Camera & getInstance ()
Public Attributes
float x
float y
bool moving = false
Private Member Functions
Camera (float _x, float _y)
Private Attributes
float xInit
float yInit
Detailed Description
Definition at line 18 of file Camera.h.
Constructor & Destructor Documentation
Camera()
astra::ui::Camera::Camera (float _x = 0.0f, float _y = 0.0f) [private]
Definition at line 19 of file Camera.cpp.
Member Function Documentation
animation()
void astra::ui::Animation::animation (float * _pos, float _posTrg, float _speed) [inline], [virtual], [inherited]
Definition at line 47 of file Animation.cpp.
Referenced by go(), goHorizontal(), goToNextPageItem(), goToPreviewPageItem(), goVertical(), astra::Launcher::popInfo(), astra::ui::ListMenu::render(), astra::ui::Selector::render(), astra::ui::TileMenu::render(), and reset().
blur()
void astra::ui::Animation::blur () [inline], [virtual], [inherited]
Definition at line 41 of file Animation.cpp.
entryAnimation()
virtual void astra::ui::Animation::entryAnimation () [inline], [virtual], [inherited]
Definition at line 13 of file Animation.h.
exitAnimation()
void astra::ui::Animation::exitAnimation () [inline], [virtual], [inherited]
Definition at line 14 of file Animation.cpp.
Referenced by astra::ui::Menu::deInit(), and astra::ui::Menu::onExit().
getInstance()
static Camera & astra::ui::Camera::getInstance () [inline], [static]
Definition at line 59 of file Camera.h.
getPosition()
std::vector< float > astra::ui::Camera::getPosition () const
Definition at line 41 of file Camera.cpp.
Referenced by astra::ui::Menu::onLoop(), and astra::ui::Menu::onOpen().
go()
void astra::ui::Camera::go (float _x, float _y)
Parameters
_pos
_posTrg
_speed
Note
only support in loop. 仅支持在循环内执行
Definition at line 53 of file Camera.cpp.
Referenced by goToListItemPage(), goToListItemRolling(), and goToTileItem().
goDirect()
void astra::ui::Camera::goDirect (float _x, float _y)
Definition at line 60 of file Camera.cpp.
goHorizontal()
void astra::ui::Camera::goHorizontal (float _x)
Definition at line 65 of file Camera.cpp.
goToListItemPage()
void astra::ui::Camera::goToListItemPage (uint8_t _index)
Definition at line 89 of file Camera.cpp.
Referenced by update().
goToListItemRolling()
void astra::ui::Camera::goToListItemRolling (const std::vector< float > & _posSelector)
Definition at line 104 of file Camera.cpp.
Referenced by update().
goToNextPageItem()
void astra::ui::Camera::goToNextPageItem ()
Definition at line 77 of file Camera.cpp.
goToPreviewPageItem()
void astra::ui::Camera::goToPreviewPageItem ()
Definition at line 83 of file Camera.cpp.
goToTileItem()
void astra::ui::Camera::goToTileItem (uint8_t _index)
Definition at line 139 of file Camera.cpp.
Referenced by update().
goVertical()
void astra::ui::Camera::goVertical (float _y)
Definition at line 71 of file Camera.cpp.
isMoving()
bool astra::ui::Camera::isMoving () const
Definition at line 146 of file Camera.cpp.
outOfView()
uint8_t astra::ui::Camera::outOfView (float _x, float _y) const
Parameters
_x
_y
Returns
0: in view, 1: upper, 2: lower
Definition at line 33 of file Camera.cpp.
Referenced by goToListItemRolling().
reset()
void astra::ui::Camera::reset ()
Definition at line 150 of file Camera.cpp.
update()
void astra::ui::Camera::update (Menu * _menu, Selector * _selector)
Definition at line 157 of file Camera.cpp.
Referenced by astra::ui::Menu::onLoop().
Member Data Documentation
moving
bool astra::ui::Camera::moving = false
Definition at line 24 of file Camera.h.
Referenced by go(), goHorizontal(), goToListItemPage(), goToListItemRolling(), goToNextPageItem(), goToPreviewPageItem(), goToTileItem(), goVertical(), isMoving(), and reset().
x
float astra::ui::Camera::x
Definition at line 23 of file Camera.h.
Referenced by Camera(), getPosition(), go(), goDirect(), goHorizontal(), goToListItemRolling(), goToTileItem(), outOfView(), and reset().
xInit
float astra::ui::Camera::xInit [private]
Definition at line 19 of file Camera.h.
Referenced by Camera(), and reset().
y
float astra::ui::Camera::y
Definition at line 23 of file Camera.h.
Referenced by Camera(), getPosition(), go(), goDirect(), goToListItemPage(), goToListItemRolling(), goToNextPageItem(), goToPreviewPageItem(), goVertical(), outOfView(), and reset().
yInit
float astra::ui::Camera::yInit [private]
Definition at line 19 of file Camera.h.
Referenced by Camera(), and reset().
The documentation for this class was generated from the following files:
astra/ui/element/page/Camera.h
astra/ui/element/page/Camera.cpp