Service Class Reference
#include <service.h>
Public Types
enum class Func { Open
, Close
, Switch
 }
Static Public Member Functions
static void run (const Func &f)
Static Private Member Functions
static void openLight ()
static void closeLight ()
static void switchLight ()
Static Private Attributes
static bool light = false
Detailed Description
Definition at line 82 of file service.h.
Member Enumeration Documentation
Func
enum class Service::Func [strong]
Enumerator
Open
Close
Switch
Definition at line 100 of file service.h.
Member Function Documentation
closeLight()
static void Service::closeLight () [inline], [static], [private]
Definition at line 90 of file service.h.
Referenced by run(), and switchLight().
openLight()
static void Service::openLight () [inline], [static], [private]
Definition at line 85 of file service.h.
Referenced by run(), and switchLight().
run()
static void Service::run (const Func & f) [inline], [static]
Definition at line 106 of file service.h.
Referenced by mqtt::onMqttMessage().
switchLight()
static void Service::switchLight () [inline], [static], [private]
Definition at line 95 of file service.h.
Referenced by run().
Member Data Documentation
light
bool Service::light = false [static], [private]
Definition at line 83 of file service.h.
Referenced by closeLight(), openLight(), and switchLight().
The documentation for this class was generated from the following files:
service/service.h
service/service.cpp