WiFiScan Class Reference
#include <WiFiScan.h>
Public Member Functions
void add (const char *title, LifecycleItem *item=nullptr)
ItemType getType () const override
void init (const std::vector< float > &_camera) override
void render (const std::vector< float > &_camera) override
uint8_t itemSize () const override
Position getItemPosition (const uint8_t _index) const override
LifecycleItem * enter () const override
void onInit () override
bool onOpen () override
void onLoop () override
void onExit () override
virtual void deInit ()
virtual Item * parentItem () const
virtual void entryAnimation ()
virtual void exitAnimation ()
virtual void blur ()
virtual void animation (float *_pos, float _posTrg, float _speed)
Static Public Member Functions
static WiFiScan & getInstance ()
Public Attributes
std::vector< Child > items
PositionForeground positionForeground {}
uint8_t selectIndex = 0
Camera * camera
Selector * selector
Item * parent = nullptr
Private Member Functions
WiFiScan ()
~WiFiScan () override=default
Detailed Description
Definition at line 76 of file WiFiScan.h.
Constructor & Destructor Documentation
WiFiScan()
WiFiScan::WiFiScan () [private]
Definition at line 200 of file WiFiScan.cpp.
~WiFiScan()
WiFiScan::~WiFiScan () [override], [private], [default]
Member Function Documentation
add()
void astra::ui::ListMenu::add (const char * title, LifecycleItem * item = nullptr) [inline], [inherited]
Definition at line 163 of file Menu.h.
Referenced by WiFiInfoItem::add_network_info(), UIConfig(), and WiFiScan().
animation()
void astra::ui::Animation::animation (float * _pos, float _posTrg, float _speed) [inline], [virtual], [inherited]
Definition at line 47 of file Animation.cpp.
Referenced by astra::ui::Camera::go(), astra::ui::Camera::goHorizontal(), astra::ui::Camera::goToNextPageItem(), astra::ui::Camera::goToPreviewPageItem(), astra::ui::Camera::goVertical(), astra::Launcher::popInfo(), astra::ui::ListMenu::render(), astra::ui::Selector::render(), astra::ui::TileMenu::render(), and astra::ui::Camera::reset().
blur()
void astra::ui::Animation::blur () [inline], [virtual], [inherited]
Definition at line 41 of file Animation.cpp.
deInit()
virtual void astra::ui::Menu::deInit () [inline], [virtual], [inherited]
Definition at line 72 of file Menu.h.
enter()
LifecycleItem * astra::ui::ListMenu::enter () const [inline], [override], [virtual], [inherited]
Implements astra::ui::Menu.
Definition at line 192 of file Menu.h.
entryAnimation()
virtual void astra::ui::Animation::entryAnimation () [inline], [virtual], [inherited]
Definition at line 13 of file Animation.h.
exitAnimation()
void astra::ui::Animation::exitAnimation () [inline], [virtual], [inherited]
Definition at line 14 of file Animation.cpp.
Referenced by astra::ui::Menu::deInit(), and astra::ui::Menu::onExit().
getInstance()
static WiFiScan & WiFiScan::getInstance () [inline], [static]
Definition at line 82 of file WiFiScan.h.
Referenced by UIConfig().
getItemPosition()
Position astra::ui::ListMenu::getItemPosition (const uint8_t _index) const [inline], [override], [virtual], [inherited]
Implements astra::ui::Menu.
Definition at line 188 of file Menu.h.
getType()
ItemType astra::ui::ListMenu::getType () const [inline], [override], [virtual], [inherited]
Reimplemented from astra::ui::LifecycleItem.
Definition at line 178 of file Menu.h.
init()
void astra::ui::ListMenu::init (const std::vector< float > & _camera) [override], [virtual], [inherited]
Implements astra::ui::Menu.
Definition at line 116 of file Menu.cpp.
itemSize()
uint8_t astra::ui::ListMenu::itemSize () const [inline], [override], [virtual], [inherited]
Implements astra::ui::Menu.
Definition at line 184 of file Menu.h.
Referenced by astra::ui::ListMenu::add(), and astra::ui::ListMenu::render().
onExit()
void astra::ui::Menu::onExit () [inline], [override], [virtual], [inherited]
Implements astra::ui::LifecycleItem.
Reimplemented in WiFiInfoItem.
Definition at line 63 of file Menu.h.
onInit()
void astra::ui::Menu::onInit () [inline], [override], [virtual], [inherited]
Implements astra::ui::LifecycleItem.
Reimplemented in WiFiInfoItem.
Definition at line 56 of file Menu.h.
onLoop()
void astra::ui::Menu::onLoop () [override], [virtual], [inherited]
Implements astra::ui::LifecycleItem.
Definition at line 23 of file Menu.cpp.
onOpen()
bool astra::ui::Menu::onOpen () [override], [virtual], [inherited]
Implements astra::ui::LifecycleItem.
Reimplemented in WiFiInfoItem.
Definition at line 14 of file Menu.cpp.
parentItem()
virtual Item * astra::ui::Menu::parentItem () const [inline], [virtual], [inherited]
Definition at line 78 of file Menu.h.
render()
void astra::ui::ListMenu::render (const std::vector< float > & _camera) [override], [virtual], [inherited]
Implements astra::ui::Menu.
Definition at line 131 of file Menu.cpp.
Member Data Documentation
camera
Camera* astra::ui::Menu::camera [inherited]
Definition at line 44 of file Menu.h.
Referenced by astra::ui::Menu::onLoop(), and astra::ui::Menu::onOpen().
items
std::vector<Child> astra::ui::ListMenu::items [inherited]
Definition at line 157 of file Menu.h.
Referenced by astra::ui::ListMenu::add(), astra::ui::ListMenu::enter(), astra::ui::ListMenu::getItemPosition(), astra::ui::Selector::go(), astra::ui::ListMenu::init(), astra::ui::ListMenu::itemSize(), and astra::ui::ListMenu::render().
parent
Item* astra::ui::Item::parent = nullptr [inherited]
Definition at line 26 of file Item.h.
Referenced by astra::ui::ListMenu::add(), astra::ui::TileMenu::add(), and astra::ui::Menu::parentItem().
positionForeground
PositionForeground astra::ui::Menu::positionForeground {} [inherited]
Definition at line 42 of file Menu.h.
Referenced by astra::ui::ListMenu::add(), astra::ui::TileMenu::add(), astra::ui::ListMenu::init(), astra::ui::TileMenu::init(), astra::ui::ListMenu::render(), and astra::ui::TileMenu::render().
selectIndex
uint8_t astra::ui::Menu::selectIndex = 0 [inherited]
Definition at line 43 of file Menu.h.
Referenced by astra::ui::ListMenu::enter(), astra::ui::TileMenu::enter(), astra::ui::Selector::go(), astra::ui::Selector::inject(), astra::ui::Selector::last(), astra::ui::Selector::next(), astra::ui::ListMenu::render(), astra::ui::Selector::render(), astra::ui::TileMenu::render(), and astra::ui::Camera::update().
selector
Selector* astra::ui::Menu::selector [inherited]
Definition at line 45 of file Menu.h.
Referenced by astra::ui::Menu::onLoop(), and astra::ui::Menu::onOpen().
The documentation for this class was generated from the following files:
application/WiFiScan.h
application/WiFiScan.cpp