game::GameOfLife::GameOfLife< WIDTH, HEIGHT > Class Template Reference
#include <game.h>
Classes
struct Board
Public Types
enum Status { Dead = 0
, Active = 1
 }
Public Member Functions
GameOfLife (int lives=width *height/2)
void restart ()
void update ()
const Board * get_board_status () const
Private Member Functions
void init (int lives=width *height/2)
Status update (int x, int y)
Static Private Member Functions
static constexpr int max (const int a, const int b)
static constexpr int min (const int a, const int b)
static void setRandomSeed ()
static unsigned long random (const long a, const long b)
Private Attributes
Board data
Board temp
Board * pBoard = &data
Board * nBoard = &temp
int gen = 0
Detailed Description
template<int WIDTH, int HEIGHT>
class game::GameOfLife::GameOfLife< WIDTH, HEIGHT >
Definition at line 32 of file game.h.
Member Enumeration Documentation
Status
template<int WIDTH, int HEIGHT>
enum game::GameOfLife::GameOfLife::Status
Enumerator
Dead
Active
Definition at line 34 of file game.h.
Constructor & Destructor Documentation
GameOfLife()
template<int WIDTH, int HEIGHT>
game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::GameOfLife (int lives = width * height / 2) [inline], [explicit]
Definition at line 97 of file game.h.
Member Function Documentation
get_board_status()
template<int WIDTH, int HEIGHT>
const Board * game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::get_board_status () const [inline]
Definition at line 125 of file game.h.
init()
template<int WIDTH, int HEIGHT>
void game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::init (int lives = width * height / 2) [inline], [private]
Definition at line 58 of file game.h.
Referenced by game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::GameOfLife(), and game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::restart().
max()
template<int WIDTH, int HEIGHT>
static constexpr int game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::max (const int a, const int b) [inline], [static], [constexpr], [private]
Definition at line 40 of file game.h.
Referenced by game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::update().
min()
template<int WIDTH, int HEIGHT>
static constexpr int game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::min (const int a, const int b) [inline], [static], [constexpr], [private]
Definition at line 44 of file game.h.
Referenced by game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::update().
random()
template<int WIDTH, int HEIGHT>
static unsigned long game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::random (const long a, const long b) [inline], [static], [private]
Definition at line 53 of file game.h.
Referenced by game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::init().
restart()
template<int WIDTH, int HEIGHT>
void game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::restart () [inline]
Definition at line 101 of file game.h.
setRandomSeed()
template<int WIDTH, int HEIGHT>
static void game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::setRandomSeed () [inline], [static], [private]
Definition at line 48 of file game.h.
Referenced by game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::init().
update() [1/2]
template<int WIDTH, int HEIGHT>
void game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::update () [inline]
Definition at line 112 of file game.h.
Referenced by game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::update().
update() [2/2]
template<int WIDTH, int HEIGHT>
Status game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::update (int x, int y) [inline], [private]
Definition at line 70 of file game.h.
Member Data Documentation
data
template<int WIDTH, int HEIGHT>
Board game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::data [private]
Definition at line 130 of file game.h.
gen
template<int WIDTH, int HEIGHT>
int game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::gen = 0 [private]
Definition at line 132 of file game.h.
Referenced by game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::update().
nBoard
template<int WIDTH, int HEIGHT>
Board * game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::nBoard = &temp [private]
Definition at line 131 of file game.h.
Referenced by game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::restart(), and game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::update().
pBoard
template<int WIDTH, int HEIGHT>
Board* game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::pBoard = &data [private]
Definition at line 131 of file game.h.
Referenced by game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::get_board_status(), game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::init(), game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::restart(), game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::update(), and game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::update().
temp
template<int WIDTH, int HEIGHT>
Board game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::temp [private]
Definition at line 130 of file game.h.
Referenced by game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::update().
The documentation for this class was generated from the following file:
game/game.h