astra::ui::Animation Class Reference
#include <Animation.h>
Public Member Functions
virtual void entryAnimation ()
virtual void exitAnimation ()
virtual void blur ()
virtual void animation (float *_pos, float _posTrg, float _speed)
virtual ~Animation ()=default
Detailed Description
Definition at line 11 of file Animation.h.
Constructor & Destructor Documentation
~Animation()
virtual astra::ui::Animation::~Animation () [virtual], [default]
Member Function Documentation
animation()
void astra::ui::Animation::animation (float * _pos, float _posTrg, float _speed) [inline], [virtual]
Definition at line 47 of file Animation.cpp.
Referenced by astra::ui::Camera::go(), astra::ui::Camera::goHorizontal(), astra::ui::Camera::goToNextPageItem(), astra::ui::Camera::goToPreviewPageItem(), astra::ui::Camera::goVertical(), astra::Launcher::popInfo(), astra::ui::ListMenu::render(), astra::ui::Selector::render(), astra::ui::TileMenu::render(), and astra::ui::Camera::reset().
blur()
void astra::ui::Animation::blur () [inline], [virtual]
Definition at line 41 of file Animation.cpp.
entryAnimation()
virtual void astra::ui::Animation::entryAnimation () [inline], [virtual]
Definition at line 13 of file Animation.h.
exitAnimation()
void astra::ui::Animation::exitAnimation () [inline], [virtual]
Definition at line 14 of file Animation.cpp.
Referenced by astra::ui::Menu::deInit(), and astra::ui::Menu::onExit().
The documentation for this class was generated from the following files:
astra/ui/element/page/Animation.h
astra/ui/element/page/Animation.cpp