astra::ui::Menu Class Reference
#include <Menu.h>
Classes
struct Position
struct PositionForeground
Public Member Functions
Menu ()
~Menu () override=default
ItemType getType () const override
void onInit () override
bool onOpen () override
void onLoop () override
void onExit () override
virtual void init (const std::vector< float > &_camera)=0
virtual void render (const std::vector< float > &_camera)=0
virtual void deInit ()
virtual uint8_t itemSize () const =0
virtual Position getItemPosition (uint8_t _index) const =0
virtual Item * parentItem () const
virtual LifecycleItem * enter () const =0
virtual void entryAnimation ()
virtual void exitAnimation ()
virtual void blur ()
virtual void animation (float *_pos, float _posTrg, float _speed)
Public Attributes
PositionForeground positionForeground {}
uint8_t selectIndex = 0
Camera * camera
Selector * selector
Item * parent = nullptr
Detailed Description
Definition at line 21 of file Menu.h.
Constructor & Destructor Documentation
Menu()
astra::ui::Menu::Menu ()
Definition at line 10 of file Menu.cpp.
~Menu()
astra::ui::Menu::~Menu () [override], [default]
Member Function Documentation
animation()
void astra::ui::Animation::animation (float * _pos, float _posTrg, float _speed) [inline], [virtual], [inherited]
Definition at line 47 of file Animation.cpp.
Referenced by astra::ui::Camera::go(), astra::ui::Camera::goHorizontal(), astra::ui::Camera::goToNextPageItem(), astra::ui::Camera::goToPreviewPageItem(), astra::ui::Camera::goVertical(), astra::Launcher::popInfo(), astra::ui::ListMenu::render(), astra::ui::Selector::render(), astra::ui::TileMenu::render(), and astra::ui::Camera::reset().
blur()
void astra::ui::Animation::blur () [inline], [virtual], [inherited]
Definition at line 41 of file Animation.cpp.
deInit()
virtual void astra::ui::Menu::deInit () [inline], [virtual]
Definition at line 72 of file Menu.h.
enter()
virtual LifecycleItem * astra::ui::Menu::enter () const [pure virtual]
Implemented in astra::ui::ListMenu, and astra::ui::TileMenu.
entryAnimation()
virtual void astra::ui::Animation::entryAnimation () [inline], [virtual], [inherited]
Definition at line 13 of file Animation.h.
exitAnimation()
void astra::ui::Animation::exitAnimation () [inline], [virtual], [inherited]
Definition at line 14 of file Animation.cpp.
Referenced by deInit(), and onExit().
getItemPosition()
virtual Position astra::ui::Menu::getItemPosition (uint8_t _index) const [pure virtual]
Implemented in astra::ui::ListMenu, and astra::ui::TileMenu.
getType()
ItemType astra::ui::Menu::getType () const [inline], [override], [virtual]
Reimplemented from astra::ui::LifecycleItem.
Reimplemented in astra::ui::TileMenu.
Definition at line 54 of file Menu.h.
init()
virtual void astra::ui::Menu::init (const std::vector< float > & _camera) [pure virtual]
Implemented in astra::ui::ListMenu, and astra::ui::TileMenu.
Referenced by onOpen().
itemSize()
virtual uint8_t astra::ui::Menu::itemSize () const [pure virtual]
Implemented in astra::ui::ListMenu, and astra::ui::TileMenu.
Referenced by astra::ui::Selector::go(), astra::ui::Selector::last(), astra::ui::Selector::next(), and onOpen().
onExit()
void astra::ui::Menu::onExit () [inline], [override], [virtual]
Implements astra::ui::LifecycleItem.
Reimplemented in WiFiInfoItem.
Definition at line 63 of file Menu.h.
onInit()
void astra::ui::Menu::onInit () [inline], [override], [virtual]
Implements astra::ui::LifecycleItem.
Reimplemented in WiFiInfoItem.
Definition at line 56 of file Menu.h.
onLoop()
void astra::ui::Menu::onLoop () [override], [virtual]
Implements astra::ui::LifecycleItem.
Definition at line 23 of file Menu.cpp.
onOpen()
bool astra::ui::Menu::onOpen () [override], [virtual]
Implements astra::ui::LifecycleItem.
Reimplemented in WiFiInfoItem.
Definition at line 14 of file Menu.cpp.
parentItem()
virtual Item * astra::ui::Menu::parentItem () const [inline], [virtual]
Definition at line 78 of file Menu.h.
render()
virtual void astra::ui::Menu::render (const std::vector< float > & _camera) [pure virtual]
Implemented in astra::ui::ListMenu, and astra::ui::TileMenu.
Referenced by onLoop().
Member Data Documentation
camera
Camera* astra::ui::Menu::camera
Definition at line 44 of file Menu.h.
Referenced by onLoop(), and onOpen().
parent
Item* astra::ui::Item::parent = nullptr [inherited]
Definition at line 26 of file Item.h.
Referenced by astra::ui::ListMenu::add(), astra::ui::TileMenu::add(), and parentItem().
positionForeground
PositionForeground astra::ui::Menu::positionForeground {}
Definition at line 42 of file Menu.h.
Referenced by astra::ui::ListMenu::add(), astra::ui::TileMenu::add(), astra::ui::ListMenu::init(), astra::ui::TileMenu::init(), astra::ui::ListMenu::render(), and astra::ui::TileMenu::render().
selectIndex
uint8_t astra::ui::Menu::selectIndex = 0
Definition at line 43 of file Menu.h.
Referenced by astra::ui::ListMenu::enter(), astra::ui::TileMenu::enter(), astra::ui::Selector::go(), astra::ui::Selector::inject(), astra::ui::Selector::last(), astra::ui::Selector::next(), astra::ui::ListMenu::render(), astra::ui::Selector::render(), astra::ui::TileMenu::render(), and astra::ui::Camera::update().
selector
Selector* astra::ui::Menu::selector
Definition at line 45 of file Menu.h.
Referenced by onLoop(), and onOpen().
The documentation for this class was generated from the following files:
astra/ui/element/page/Menu.h
astra/ui/element/page/Menu.cpp