WiFiScan::WiFiInfoItem Class Reference
#include <WiFiScan.h>
Classes
class ConnectTo
Public Member Functions
void onInit () override
bool onOpen () override
void onExit () override
Static Public Member Functions
static WiFiInfoItem & getInstance ()
Private Member Functions
WiFiInfoItem ()=default
void showNetworks ()
Private Attributes
bool inited = false
std::vector< ConnectTo * > connects
Detailed Description
Definition at line 108 of file WiFiScan.h.
Constructor & Destructor Documentation
WiFiInfoItem()
WiFiScan::WiFiInfoItem::WiFiInfoItem () [private], [default]
Member Function Documentation
getInstance()
static WiFiInfoItem & WiFiScan::WiFiInfoItem::getInstance () [inline], [static]
Definition at line 208 of file WiFiScan.h.
Referenced by WiFiScan::WiFiScan().
onExit()
void WiFiScan::WiFiInfoItem::onExit () [inline], [override]
Definition at line 199 of file WiFiScan.h.
onInit()
void WiFiScan::WiFiInfoItem::onInit () [inline], [override]
Definition at line 186 of file WiFiScan.h.
Referenced by onOpen().
onOpen()
bool WiFiScan::WiFiInfoItem::onOpen () [inline], [override]
Definition at line 190 of file WiFiScan.h.
showNetworks()
void WiFiScan::WiFiInfoItem::showNetworks () [inline], [private]
Definition at line 176 of file WiFiScan.h.
Referenced by onInit().
Member Data Documentation
connects
std::vector<ConnectTo *> WiFiScan::WiFiInfoItem::connects [private]
Definition at line 172 of file WiFiScan.h.
Referenced by onExit(), and showNetworks().
inited
bool WiFiScan::WiFiInfoItem::inited = false [private]
Definition at line 170 of file WiFiScan.h.
Referenced by onExit(), and onOpen().
The documentation for this class was generated from the following file:
application/WiFiScan.h