MyHAL Class Reference
#include <myhal.hpp>
Public Member Functions
MyHAL ()=default
~MyHAL () override=default
const char * type () override
void init () override
void _beep (float _freq) override
buzzer.
void _beepStop () override
void _setBeepVol (uint8_t _vol) override
void _screenOn () override
void _screenOff () override
bool _getKey (key::KEY_INDEX _keyIndex) override
key.
void _updateConfig () override
system config.
void u8g2_init ()
void * _getCanvasBuffer () override
uint8_t _getBufferTileHeight () override
uint8_t _getBufferTileWidth () override
void _canvasUpdate () override
void _canvasClear () override
void _setFont (const uint8_t *_font) override
uint8_t _getFontWidth (const char *_text) override
uint8_t _getFontHeight () override
void _setDrawType (uint8_t _type) override
void _drawPixel (const float _x, const float _y) override
void _drawLine (float _x, float _y, float _x2, float _y2) override
void _drawEnglish (const float _x, const float _y, const char *_text) override
void _drawChinese (const float _x, const float _y, const char *_text) override
void _drawVDottedLine (const float _x, const float _y, const float _h) override
void _drawHDottedLine (const float _x, const float _y, const float _l) override
void _drawVLine (const float _x, const float _y, const float _h) override
void _drawHLine (const float _x, const float _y, const float _l) override
void _drawBMP (const float _x, const float _y, const float _w, const float _h, const unsigned char *_bitMap) override
void _drawBox (const float _x, const float _y, const float _w, const float _h) override
void _drawRBox (const float _x, const float _y, const float _w, const float _h, const float _r) override
void _drawFrame (const float _x, const float _y, const float _w, const float _h) override
void _drawRFrame (const float _x, const float _y, const float _w, const float _h, const float _r) override
virtual void _drawBMP (float _x, float _y, float _w, float _h, const uint8_t *_bitMap)=0
virtual void _printInfo (const char *_msg)
virtual void _delay (unsigned long _mill)=0
virtual unsigned long _millis ()=0
virtual unsigned long _getTick ()=0
virtual void _setRandomSeed ()
virtual unsigned long _random ()
virtual bool _getAnyKey ()
virtual void _keyScan ()
key scanner default. 默认按键扫描函数
virtual void _keyTest ()
default key tester. 默认按键测试函数
Static Public Member Functions
static MyHAL & getInstance ()
static HAL * get ()
static bool check ()
static bool inject (HAL *_hal)
static void destroy ()
static void * getCanvasBuffer ()
static uint8_t getBufferTileHeight ()
static uint8_t getBufferTileWidth ()
static void canvasUpdate ()
static void canvasClear ()
static void setFont (const uint8_t *_font)
static uint8_t getFontWidth (const char *_text)
static uint8_t getFontHeight ()
static void setDrawType (uint8_t _type)
static void drawPixel (float _x, float _y)
static void drawLine (float _x, float _y, float _x2, float _y2)
static void drawEnglish (float _x, float _y, const char *_text)
static void drawChinese (float _x, float _y, const char *_text)
static void drawVDottedLine (float _x, float _y, float _h)
static void drawHDottedLine (float _x, float _y, float _l)
static void drawVLine (float _x, float _y, float _h)
static void drawHLine (float _x, float _y, float _l)
static void drawBMP (float _x, float _y, float _w, float _h, const uint8_t *_bitMap)
static void drawBox (float _x, float _y, float _w, float _h)
static void drawRBox (float _x, float _y, float _w, float _h, float _r)
static void drawFrame (float _x, float _y, float _w, float _h)
static void drawRFrame (float _x, float _y, float _w, float _h, float _r)
static void printInfo (const char *_msg)
static void printInfo (const String &_msg)
static void showInfo ()
static void cleanInfo ()
static void cancelInfo ()
static void delay (unsigned long _mill)
system timers.
static unsigned long millis ()
static unsigned long getTick ()
static void setRandomSeed ()
static unsigned long random ()
static void beep (float _freq)
buzzer.
static void beepStop ()
static void setBeepVol (uint8_t _vol)
static void screenOn ()
static void screenOff ()
static bool getKey (key::KEY_INDEX _keyIndex)
key.
static bool getAnyKey ()
static void keyScan ()
static void keyTest ()
static const sys::config & getSystemConfig ()
system config.
static void updateConfig ()
Public Attributes
U8G2_SSD1306_128X64_NONAME_F_4W_HW_SPI u8g2 {U8G2_R0, OLED_CS_PIN, OLED_DC_PIN, OLED_RES_PIN}
Protected Attributes
key::keyAction key [key::KEY_NUM] {static_cast<key::keyAction>(0)}
Detailed Description
Definition at line 15 of file myhal.hpp.
Constructor & Destructor Documentation
MyHAL()
MyHAL::MyHAL () [default]
~MyHAL()
MyHAL::~MyHAL () [override], [default]
Member Function Documentation
_beep()
void MyHAL::_beep (float _freq) [inline], [override], [virtual]
buzzer.
Implements HAL.
Definition at line 33 of file myhal.hpp.
_beepStop()
void MyHAL::_beepStop () [inline], [override], [virtual]
Reimplemented from HAL.
Definition at line 36 of file myhal.hpp.
_canvasClear()
void U8G2BIND::_canvasClear () [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 44 of file U8g2Bind.h.
_canvasUpdate()
void U8G2BIND::_canvasUpdate () [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 40 of file U8g2Bind.h.
_delay()
virtual void HAL::_delay (unsigned long _mill) [pure virtual], [inherited]
Implemented in ARDUINOBIND.
Referenced by HAL::delay().
_drawBMP() [1/2]
virtual void HAL::_drawBMP (float _x, float _y, float _w, float _h, const uint8_t * _bitMap) [pure virtual], [inherited]
Referenced by HAL::drawBMP().
_drawBMP() [2/2]
void U8G2BIND::_drawBMP (const float _x, const float _y, const float _w, const float _h, const unsigned char * _bitMap) [inline], [override], [inherited]
Definition at line 111 of file U8g2Bind.h.
_drawBox()
void U8G2BIND::_drawBox (const float _x, const float _y, const float _w, const float _h) [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 115 of file U8g2Bind.h.
_drawChinese()
void U8G2BIND::_drawChinese (const float _x, const float _y, const char * _text) [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 81 of file U8g2Bind.h.
_drawEnglish()
void U8G2BIND::_drawEnglish (const float _x, const float _y, const char * _text) [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 77 of file U8g2Bind.h.
_drawFrame()
void U8G2BIND::_drawFrame (const float _x, const float _y, const float _w, const float _h) [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 123 of file U8g2Bind.h.
_drawHDottedLine()
void U8G2BIND::_drawHDottedLine (const float _x, const float _y, const float _l) [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 94 of file U8g2Bind.h.
_drawHLine()
void U8G2BIND::_drawHLine (const float _x, const float _y, const float _l) [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 107 of file U8g2Bind.h.
_drawLine()
void U8G2BIND::_drawLine (float _x, float _y, float _x2, float _y2) [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 70 of file U8g2Bind.h.
_drawPixel()
void U8G2BIND::_drawPixel (const float _x, const float _y) [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 66 of file U8g2Bind.h.
Referenced by U8G2BIND::_drawHDottedLine(), and U8G2BIND::_drawVDottedLine().
_drawRBox()
void U8G2BIND::_drawRBox (const float _x, const float _y, const float _w, const float _h, const float _r) [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 119 of file U8g2Bind.h.
_drawRFrame()
void U8G2BIND::_drawRFrame (const float _x, const float _y, const float _w, const float _h, const float _r) [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 127 of file U8g2Bind.h.
_drawVDottedLine()
void U8G2BIND::_drawVDottedLine (const float _x, const float _y, const float _h) [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 85 of file U8g2Bind.h.
_drawVLine()
void U8G2BIND::_drawVLine (const float _x, const float _y, const float _h) [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 103 of file U8g2Bind.h.
_getAnyKey()
bool HAL::_getAnyKey () [virtual], [inherited]
Definition at line 60 of file hal.cpp.
Referenced by HAL::getAnyKey().
_getBufferTileHeight()
uint8_t U8G2BIND::_getBufferTileHeight () [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 32 of file U8g2Bind.h.
_getBufferTileWidth()
uint8_t U8G2BIND::_getBufferTileWidth () [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 36 of file U8g2Bind.h.
_getCanvasBuffer()
void * U8G2BIND::_getCanvasBuffer () [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 28 of file U8g2Bind.h.
_getFontHeight()
uint8_t U8G2BIND::_getFontHeight () [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 58 of file U8g2Bind.h.
_getFontWidth()
uint8_t U8G2BIND::_getFontWidth (const char * _text) [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 54 of file U8g2Bind.h.
_getKey()
bool MyHAL::_getKey (key::KEY_INDEX _keyIndex) [inline], [override], [virtual]
key.
Reimplemented from HAL.
Definition at line 61 of file myhal.hpp.
_getTick()
virtual unsigned long HAL::_getTick () [pure virtual], [inherited]
Implemented in ARDUINOBIND.
Referenced by HAL::getTick().
_keyScan()
void HAL::_keyScan () [virtual], [inherited]
key scanner default. 默认按键扫描函数
Note
run per 5 ms.
Returns
key::keyValue
Todo
Todo test this fucking function.
Definition at line 74 of file hal.cpp.
Referenced by HAL::keyScan().
_keyTest()
void HAL::_keyTest () [virtual], [inherited]
default key tester. 默认按键测试函数
Definition at line 135 of file hal.cpp.
Referenced by HAL::keyTest().
_millis()
virtual unsigned long HAL::_millis () [pure virtual], [inherited]
Implemented in ARDUINOBIND.
Referenced by HAL::millis().
_printInfo()
void HAL::_printInfo (const char * _msg) [virtual], [inherited]
Definition at line 48 of file hal.cpp.
Referenced by HAL::printInfo(), and HAL::printInfo().
_random()
virtual unsigned long HAL::_random () [inline], [virtual], [inherited]
Reimplemented in ARDUINOBIND.
Definition at line 243 of file hal.h.
Referenced by HAL::random().
_screenOff()
void MyHAL::_screenOff () [inline], [override], [virtual]
Reimplemented from HAL.
Definition at line 50 of file myhal.hpp.
_screenOn()
void MyHAL::_screenOn () [inline], [override], [virtual]
Reimplemented from HAL.
Definition at line 43 of file myhal.hpp.
_setBeepVol()
void MyHAL::_setBeepVol (uint8_t _vol) [inline], [override], [virtual]
Reimplemented from HAL.
Definition at line 39 of file myhal.hpp.
_setDrawType()
void U8G2BIND::_setDrawType (uint8_t _type) [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 62 of file U8g2Bind.h.
_setFont()
void U8G2BIND::_setFont (const uint8_t * _font) [inline], [override], [virtual], [inherited]
Implements HAL.
Definition at line 48 of file U8g2Bind.h.
_setRandomSeed()
virtual void HAL::_setRandomSeed () [inline], [virtual], [inherited]
Reimplemented in ARDUINOBIND.
Definition at line 238 of file hal.h.
Referenced by HAL::setRandomSeed().
_updateConfig()
void MyHAL::_updateConfig () [inline], [override], [virtual]
system config.
Reimplemented from HAL.
Definition at line 69 of file myhal.hpp.
beep()
static void HAL::beep (float _freq) [inline], [static], [inherited]
buzzer.
Definition at line 250 of file hal.h.
beepStop()
static void HAL::beepStop () [inline], [static], [inherited]
Definition at line 254 of file hal.h.
cancelInfo()
void HAL::cancelInfo () [static], [inherited]
Definition at line 44 of file hal.cpp.
Referenced by WiFiScanItem::onLoop(), NetworkManager::update(), and WiFiInfoItem::ConnectTo::update().
canvasClear()
static void HAL::canvasClear () [inline], [static], [inherited]
Definition at line 108 of file hal.h.
Referenced by astra::drawLogo(), astra::Launcher::loop(), astra::Launcher::popInfo(), HAL::showInfo(), block::update(), game::GameOfLife::Runner::update(), and mqtt::MqttView::update().
canvasUpdate()
static void HAL::canvasUpdate () [inline], [static], [inherited]
Definition at line 104 of file hal.h.
Referenced by astra::drawLogo(), astra::Launcher::loop(), astra::Launcher::popInfo(), HAL::showInfo(), block::update(), game::GameOfLife::Runner::update(), and mqtt::MqttView::update().
check()
static bool HAL::check () [inline], [static], [inherited]
Definition at line 66 of file hal.h.
cleanInfo()
void HAL::cleanInfo () [static], [inherited]
Definition at line 40 of file hal.cpp.
Referenced by WiFiScanItem::onInit(), DeviceInfo::setup(), and NetworkManager::setup().
delay()
static void HAL::delay (unsigned long _mill) [inline], [static], [inherited]
system timers.
Definition at line 221 of file hal.h.
Referenced by ARDUINOBIND::_delay(), astra::ui::Animation::exitAnimation(), app::App::HAL_INIT(), WiFiScanItem::onLoop(), block::update(), DeviceInfo::update(), game::GameOfLife::Runner::update(), NetworkManager::update(), and WiFiInfoItem::ConnectTo::update().
destroy()
void HAL::destroy () [static], [inherited]
Definition at line 6 of file hal.cpp.
drawBMP()
static void HAL::drawBMP (float _x, float _y, float _w, float _h, const uint8_t * _bitMap) [inline], [static], [inherited]
Definition at line 163 of file hal.h.
Referenced by astra::ui::TileMenu::render().
drawBox()
static void HAL::drawBox (float _x, float _y, float _w, float _h) [inline], [static], [inherited]
Definition at line 173 of file hal.h.
Referenced by astra::drawLogo(), astra::ui::ListMenu::render(), and astra::ui::TileMenu::render().
drawChinese()
static void HAL::drawChinese (float _x, float _y, const char * _text) [inline], [static], [inherited]
Definition at line 143 of file hal.h.
Referenced by astra::ui::ListMenu::render(), astra::ui::Selector::render(), and mqtt::MqttView::update().
drawEnglish()
static void HAL::drawEnglish (float _x, float _y, const char * _text) [inline], [static], [inherited]
Definition at line 139 of file hal.h.
Referenced by astra::drawLogo(), astra::Launcher::popInfo(), and HAL::showInfo().
drawFrame()
static void HAL::drawFrame (float _x, float _y, float _w, float _h) [inline], [static], [inherited]
Definition at line 187 of file hal.h.
drawHDottedLine()
static void HAL::drawHDottedLine (float _x, float _y, float _l) [inline], [static], [inherited]
Definition at line 151 of file hal.h.
Referenced by astra::ui::TileMenu::render().
drawHLine()
static void HAL::drawHLine (float _x, float _y, float _l) [inline], [static], [inherited]
Definition at line 159 of file hal.h.
Referenced by astra::drawLogo(), astra::ui::ListMenu::render(), astra::ui::Selector::render(), and astra::ui::TileMenu::render().
drawLine()
static void HAL::drawLine (float _x, float _y, float _x2, float _y2) [inline], [static], [inherited]
Definition at line 133 of file hal.h.
Referenced by block::update().
drawPixel()
static void HAL::drawPixel (float _x, float _y) [inline], [static], [inherited]
Definition at line 129 of file hal.h.
Referenced by astra::ui::Selector::render(), astra::ui::TileMenu::render(), and game::GameOfLife::Runner::update().
drawRBox()
static void HAL::drawRBox (float _x, float _y, float _w, float _h, float _r) [inline], [static], [inherited]
Definition at line 177 of file hal.h.
Referenced by astra::Launcher::popInfo(), and astra::ui::Selector::render().
drawRFrame()
static void HAL::drawRFrame (float _x, float _y, float _w, float _h, float _r) [inline], [static], [inherited]
Definition at line 191 of file hal.h.
Referenced by astra::Launcher::popInfo().
drawVDottedLine()
static void HAL::drawVDottedLine (float _x, float _y, float _h) [inline], [static], [inherited]
Definition at line 147 of file hal.h.
drawVLine()
static void HAL::drawVLine (float _x, float _y, float _h) [inline], [static], [inherited]
Definition at line 155 of file hal.h.
Referenced by astra::drawLogo(), astra::ui::ListMenu::render(), and astra::ui::Selector::render().
get()
static HAL * HAL::get () [inline], [static], [inherited]
Definition at line 62 of file hal.h.
Referenced by HAL::beep(), HAL::beepStop(), HAL::canvasClear(), HAL::canvasUpdate(), HAL::delay(), HAL::drawBMP(), HAL::drawBox(), HAL::drawChinese(), HAL::drawEnglish(), HAL::drawFrame(), HAL::drawHDottedLine(), HAL::drawHLine(), HAL::drawLine(), HAL::drawPixel(), HAL::drawRBox(), HAL::drawRFrame(), HAL::drawVDottedLine(), HAL::drawVLine(), HAL::getAnyKey(), HAL::getBufferTileHeight(), HAL::getBufferTileWidth(), HAL::getCanvasBuffer(), HAL::getFontHeight(), HAL::getFontWidth(), HAL::getKey(), HAL::getTick(), HAL::keyScan(), HAL::keyTest(), HAL::millis(), HAL::printInfo(), HAL::printInfo(), HAL::random(), HAL::screenOff(), HAL::screenOn(), HAL::setBeepVol(), HAL::setDrawType(), HAL::setFont(), HAL::setRandomSeed(), and HAL::updateConfig().
getAnyKey()
static bool HAL::getAnyKey () [inline], [static], [inherited]
Definition at line 281 of file hal.h.
Referenced by HAL::_keyScan().
getBufferTileHeight()
static uint8_t HAL::getBufferTileHeight () [inline], [static], [inherited]
Definition at line 96 of file hal.h.
Referenced by astra::ui::Animation::blur(), and astra::ui::Animation::exitAnimation().
getBufferTileWidth()
static uint8_t HAL::getBufferTileWidth () [inline], [static], [inherited]
Definition at line 100 of file hal.h.
Referenced by astra::ui::Animation::blur(), and astra::ui::Animation::exitAnimation().
getCanvasBuffer()
static void * HAL::getCanvasBuffer () [inline], [static], [inherited]
Definition at line 92 of file hal.h.
Referenced by astra::ui::Animation::blur(), and astra::ui::Animation::exitAnimation().
getFontHeight()
static uint8_t HAL::getFontHeight () [inline], [static], [inherited]
Definition at line 120 of file hal.h.
Referenced by HAL::_printInfo(), astra::Launcher::popInfo(), HAL::showInfo(), and mqtt::MqttView::update().
getFontWidth()
static uint8_t HAL::getFontWidth (const char * _text) [inline], [static], [inherited]
Definition at line 116 of file hal.h.
Referenced by astra::drawLogo(), astra::ui::Selector::go(), astra::Launcher::popInfo(), astra::ui::Selector::render(), and wrapText().
getInstance()
static MyHAL & MyHAL::getInstance () [inline], [static]
Definition at line 72 of file myhal.hpp.
Referenced by app::App::HAL_INIT().
getKey()
static bool HAL::getKey (key::KEY_INDEX _keyIndex) [inline], [static], [inherited]
key.
Definition at line 278 of file hal.h.
Referenced by HAL::_getAnyKey(), and HAL::_keyScan().
getSystemConfig()
static const sys::config & HAL::getSystemConfig () [inline], [static], [inherited]
system config.
Definition at line 301 of file hal.h.
Referenced by HAL::_printInfo(), and astra::drawLogo().
getTick()
static unsigned long HAL::getTick () [inline], [static], [inherited]
Definition at line 232 of file hal.h.
init()
void MyHAL::init () [inline], [override], [virtual]
Reimplemented from HAL.
Definition at line 26 of file myhal.hpp.
inject()
static bool HAL::inject (HAL * _hal) [inline], [static], [inherited]
Definition at line 70 of file hal.h.
Referenced by app::App::HAL_INIT().
keyScan()
static void HAL::keyScan () [inline], [static], [inherited]
Definition at line 289 of file hal.h.
keyTest()
static void HAL::keyTest () [inline], [static], [inherited]
Definition at line 293 of file hal.h.
millis()
static unsigned long HAL::millis () [inline], [static], [inherited]
Definition at line 228 of file hal.h.
Referenced by ARDUINOBIND::_millis().
printInfo() [1/2]
static void HAL::printInfo (const char * _msg) [inline], [static], [inherited]
Definition at line 201 of file hal.h.
Referenced by app::App::HAL_INIT(), WiFiScanItem::onInit(), WiFiScanItem::onLoop(), DeviceInfo::update(), NetworkManager::update(), and WiFiInfoItem::ConnectTo::update().
printInfo() [2/2]
static void HAL::printInfo (const String & _msg) [inline], [static], [inherited]
Definition at line 205 of file hal.h.
random()
static unsigned long HAL::random () [inline], [static], [inherited]
Definition at line 241 of file hal.h.
Referenced by astra::drawLogo(), and game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::random().
screenOff()
static void HAL::screenOff () [inline], [static], [inherited]
Definition at line 269 of file hal.h.
screenOn()
static void HAL::screenOn () [inline], [static], [inherited]
Definition at line 264 of file hal.h.
setBeepVol()
static void HAL::setBeepVol (uint8_t _vol) [inline], [static], [inherited]
Definition at line 259 of file hal.h.
setDrawType()
static void HAL::setDrawType (uint8_t _type) [inline], [static], [inherited]
Definition at line 124 of file hal.h.
Referenced by astra::drawLogo(), astra::Launcher::popInfo(), astra::ui::ListMenu::render(), astra::ui::Selector::render(), astra::ui::TileMenu::render(), and HAL::showInfo().
setFont()
static void HAL::setFont (const uint8_t * _font) [inline], [static], [inherited]
Definition at line 112 of file hal.h.
Referenced by astra::drawLogo().
setRandomSeed()
static void HAL::setRandomSeed () [inline], [static], [inherited]
Definition at line 236 of file hal.h.
Referenced by astra::drawLogo(), and game::GameOfLife::GameOfLife< WIDTH, HEIGHT >::setRandomSeed().
showInfo()
void HAL::showInfo () [static], [inherited]
Definition at line 24 of file hal.cpp.
Referenced by HAL::_printInfo(), WiFiScanItem::onLoop(), NetworkManager::update(), and WiFiInfoItem::ConnectTo::update().
type()
const char * MyHAL::type () [inline], [override], [virtual]
Reimplemented from HAL.
Definition at line 22 of file myhal.hpp.
u8g2_init()
void U8G2BIND::u8g2_init () [inline], [inherited]
Definition at line 21 of file U8g2Bind.h.
Referenced by init().
updateConfig()
static void HAL::updateConfig () [inline], [static], [inherited]
Definition at line 304 of file hal.h.
Member Data Documentation
key
key::keyAction HAL::key[key::KEY_NUM] {static_cast<key::keyAction>(0)} [protected], [inherited]
Definition at line 286 of file hal.h.
u8g2
U8G2_SSD1306_128X64_NONAME_F_4W_HW_SPI U8G2BIND::u8g2 {U8G2_R0, OLED_CS_PIN, OLED_DC_PIN, OLED_RES_PIN} [inherited]
Definition at line 19 of file U8g2Bind.h.
Referenced by U8G2BIND::_canvasClear(), U8G2BIND::_canvasUpdate(), U8G2BIND::_drawBMP(), U8G2BIND::_drawBox(), U8G2BIND::_drawChinese(), U8G2BIND::_drawEnglish(), U8G2BIND::_drawFrame(), U8G2BIND::_drawHLine(), U8G2BIND::_drawLine(), U8G2BIND::_drawPixel(), U8G2BIND::_drawRBox(), U8G2BIND::_drawRFrame(), U8G2BIND::_drawVLine(), U8G2BIND::_getBufferTileHeight(), U8G2BIND::_getBufferTileWidth(), U8G2BIND::_getCanvasBuffer(), U8G2BIND::_getFontHeight(), U8G2BIND::_getFontWidth(), U8G2BIND::_setDrawType(), U8G2BIND::_setFont(), and U8G2BIND::u8g2_init().
The documentation for this class was generated from the following file:
hal/myhal.hpp