app::App Class Reference
#include <app.h>
Public Member Functions
void setup ()
void loop ()
Static Public Member Functions
static App & getInstance ()
Private Member Functions
App ()
void UI_INIT ()
void WIFI_INIT ()
void MQTT_INIT ()
void SERVICE_INIT ()
void add (Service *activity)
Static Private Member Functions
static void HAL_INIT ()
static void SERIAL_INIT ()
Private Attributes
std::vector< Service * > _service_list
Detailed Description
Definition at line 48 of file app.h.
Constructor & Destructor Documentation
App()
app::App::App () [private]
Definition at line 70 of file app.cpp.
Member Function Documentation
add()
void app::App::add (Service * activity) [private]
Definition at line 25 of file app.cpp.
Referenced by MQTT_INIT(), and UI_INIT().
getInstance()
App & app::App::getInstance () [static]
Definition at line 20 of file app.cpp.
Referenced by loop(), and setup().
HAL_INIT()
void app::App::HAL_INIT () [static], [private]
Definition at line 29 of file app.cpp.
Referenced by App().
loop()
void app::App::loop ()
Definition at line 86 of file app.cpp.
Referenced by loop().
MQTT_INIT()
void app::App::MQTT_INIT () [private]
Definition at line 61 of file app.cpp.
Referenced by App().
SERIAL_INIT()
void app::App::SERIAL_INIT () [static], [private]
Definition at line 46 of file app.cpp.
Referenced by App().
SERVICE_INIT()
void app::App::SERVICE_INIT () [private]
Definition at line 65 of file app.cpp.
Referenced by App().
setup()
void app::App::setup ()
Definition at line 78 of file app.cpp.
Referenced by setup().
UI_INIT()
void app::App::UI_INIT () [private]
Definition at line 53 of file app.cpp.
Referenced by App().
WIFI_INIT()
void app::App::WIFI_INIT () [private]
Definition at line 57 of file app.cpp.
Member Data Documentation
_service_list
std::vector<Service *> app::App::_service_list [private]
Definition at line 49 of file app.h.
Referenced by add(), loop(), and setup().
The documentation for this class was generated from the following files:
app/app.h
app/app.cpp