astra::ui::Selector Class Reference
#include <Selector.h>
Public Member Functions
std::vector< float > getPosition ()
void last ()
void next ()
void go (uint8_t _index)
bool inject (Menu *_menu)
bool destroy ()
void render (const std::vector< float > &_camera)
virtual void entryAnimation ()
virtual void exitAnimation ()
virtual void blur ()
virtual void animation (float *_pos, float _posTrg, float _speed)
Static Public Member Functions
static Selector & getInstance ()
Public Attributes
float x = 0
float xTrg = 0
float y = 0
float yTrg = 0
xx xx xx xx xx xx xx xx xx
struct {
 float w = 0
 float wTrg = 0
 float h = 0
 float hTrg = 0
};
xx xx xx xx xx xx xx xx xx
struct {
 float yText = 0
 float yTextTrg = 0
};
Private Member Functions
Selector ()=default
Private Attributes
Menu * menu = nullptr
Detailed Description
Definition at line 15 of file Selector.h.
Constructor & Destructor Documentation
Selector()
astra::ui::Selector::Selector () [private], [default]
Member Function Documentation
animation()
void astra::ui::Animation::animation (float * _pos, float _posTrg, float _speed) [inline], [virtual], [inherited]
Definition at line 47 of file Animation.cpp.
Referenced by astra::ui::Camera::go(), astra::ui::Camera::goHorizontal(), astra::ui::Camera::goToNextPageItem(), astra::ui::Camera::goToPreviewPageItem(), astra::ui::Camera::goVertical(), astra::Launcher::popInfo(), astra::ui::ListMenu::render(), render(), astra::ui::TileMenu::render(), and astra::ui::Camera::reset().
blur()
void astra::ui::Animation::blur () [inline], [virtual], [inherited]
Definition at line 41 of file Animation.cpp.
destroy()
bool astra::ui::Selector::destroy ()
Definition at line 79 of file Selector.cpp.
entryAnimation()
virtual void astra::ui::Animation::entryAnimation () [inline], [virtual], [inherited]
Definition at line 13 of file Animation.h.
exitAnimation()
void astra::ui::Animation::exitAnimation () [inline], [virtual], [inherited]
Definition at line 14 of file Animation.cpp.
Referenced by astra::ui::Menu::deInit(), and astra::ui::Menu::onExit().
getInstance()
static Selector & astra::ui::Selector::getInstance () [inline], [static]
Definition at line 53 of file Selector.h.
getPosition()
std::vector< float > astra::ui::Selector::getPosition ()
Definition at line 140 of file Selector.cpp.
Referenced by astra::ui::Camera::update().
go()
void astra::ui::Selector::go (uint8_t _index)
Definition at line 9 of file Selector.cpp.
Referenced by inject(), last(), and next().
inject()
bool astra::ui::Selector::inject (Menu * _menu)
Definition at line 69 of file Selector.cpp.
Referenced by astra::ui::Menu::onOpen().
last()
void astra::ui::Selector::last ()
Definition at line 144 of file Selector.cpp.
next()
void astra::ui::Selector::next ()
Definition at line 156 of file Selector.cpp.
render()
void astra::ui::Selector::render (const std::vector< float > & _camera)
Definition at line 85 of file Selector.cpp.
Referenced by astra::ui::Menu::onLoop().
Member Data Documentation
[struct]
struct { ... } astra::ui::Selector
[struct]
struct { ... } astra::ui::Selector
h
float astra::ui::Selector::h = 0
Definition at line 26 of file Selector.h.
Referenced by render().
hTrg
float astra::ui::Selector::hTrg = 0
Definition at line 26 of file Selector.h.
Referenced by go(), and render().
menu
Menu* astra::ui::Selector::menu = nullptr [private]
Definition at line 16 of file Selector.h.
Referenced by destroy(), go(), inject(), last(), next(), and render().
w
float astra::ui::Selector::w = 0
Definition at line 25 of file Selector.h.
Referenced by render().
wTrg
float astra::ui::Selector::wTrg = 0
Definition at line 25 of file Selector.h.
Referenced by go(), and render().
x
float astra::ui::Selector::x = 0
Definition at line 21 of file Selector.h.
Referenced by render().
xTrg
float astra::ui::Selector::xTrg = 0
Definition at line 21 of file Selector.h.
Referenced by getPosition(), go(), and render().
y
float astra::ui::Selector::y = 0
Definition at line 22 of file Selector.h.
Referenced by render().
yText
float astra::ui::Selector::yText = 0
Definition at line 31 of file Selector.h.
Referenced by go(), and render().
yTextTrg
float astra::ui::Selector::yTextTrg = 0
Definition at line 31 of file Selector.h.
Referenced by go(), and render().
yTrg
float astra::ui::Selector::yTrg = 0
Definition at line 22 of file Selector.h.
Referenced by getPosition(), go(), and render().
The documentation for this class was generated from the following files:
astra/ui/element/page/Selector.h
astra/ui/element/page/Selector.cpp