astra::Launcher Class Reference
#include <launcher.h>
Public Member Functions
Launcher (ui::LifecycleItem *menu)
~Launcher () override
void popInfo (const char *_info, uint16_t _time)
bool open ()
bool close ()
void setup () override
void loop () override
virtual void entryAnimation ()
virtual void exitAnimation ()
virtual void blur ()
virtual void animation (float *_pos, float _posTrg, float _speed)
Private Attributes
ui::LifecycleItem * app
uint64_t time
Detailed Description
Definition at line 15 of file launcher.h.
Constructor & Destructor Documentation
Launcher()
astra::Launcher::Launcher (ui::LifecycleItem * menu) [explicit]
Definition at line 14 of file launcher.cpp.
~Launcher()
astra::Launcher::~Launcher () [override], [default]
Member Function Documentation
animation()
void astra::ui::Animation::animation (float * _pos, float _posTrg, float _speed) [inline], [virtual], [inherited]
Definition at line 47 of file Animation.cpp.
Referenced by astra::ui::Camera::go(), astra::ui::Camera::goHorizontal(), astra::ui::Camera::goToNextPageItem(), astra::ui::Camera::goToPreviewPageItem(), astra::ui::Camera::goVertical(), popInfo(), astra::ui::ListMenu::render(), astra::ui::Selector::render(), astra::ui::TileMenu::render(), and astra::ui::Camera::reset().
blur()
void astra::ui::Animation::blur () [inline], [virtual], [inherited]
Definition at line 41 of file Animation.cpp.
close()
bool astra::Launcher::close ()
Definition at line 99 of file launcher.cpp.
Referenced by loop().
entryAnimation()
virtual void astra::ui::Animation::entryAnimation () [inline], [virtual], [inherited]
Definition at line 13 of file Animation.h.
exitAnimation()
void astra::ui::Animation::exitAnimation () [inline], [virtual], [inherited]
Definition at line 14 of file Animation.cpp.
Referenced by astra::ui::Menu::deInit(), and astra::ui::Menu::onExit().
loop()
void astra::Launcher::loop () [override], [virtual]
Implements app::Service.
Definition at line 132 of file launcher.cpp.
open()
bool astra::Launcher::open ()
Definition at line 61 of file launcher.cpp.
Referenced by loop().
popInfo()
void astra::Launcher::popInfo (const char * _info, uint16_t _time)
Definition at line 21 of file launcher.cpp.
Referenced by close(), and open().
setup()
void astra::Launcher::setup () [override], [virtual]
Implements app::Service.
Definition at line 126 of file launcher.cpp.
Member Data Documentation
app
ui::LifecycleItem* astra::Launcher::app [private]
Definition at line 16 of file launcher.h.
Referenced by loop(), and open().
time
uint64_t astra::Launcher::time [private]
Definition at line 20 of file launcher.h.
Referenced by popInfo().
The documentation for this class was generated from the following files:
astra/ui/launcher.h
astra/ui/launcher.cpp