mqtt Namespace Reference
Classes
class Message
class MqttClient
class MqttView
Functions
void connectToMqtt ()
void WiFiEvent (arduino_event_id_t event)
void onMqttConnect (bool sessionPresent)
void onMqttDisconnect (AsyncMqttClientDisconnectReason reason)
void onMqttSubscribe (uint16_t packetId, uint8_t qos)
void onMqttUnsubscribe (uint16_t packetId)
void onMqttMessage (char *topic, char *payload, AsyncMqttClientMessageProperties properties, size_t len, size_t index, size_t total)
void onMqttPublish (uint16_t packetId)
void WiFiEvent (WiFiEvent_t event)
Variables
AsyncMqttClient mqttClient
TimerHandle_t mqttReconnectTimer
Function Documentation
connectToMqtt()
void mqtt::connectToMqtt ()
Definition at line 30 of file mqtt.cpp.
Referenced by mqtt::MqttClient::setup(), and WiFiEvent().
onMqttConnect()
void mqtt::onMqttConnect (bool sessionPresent)
Definition at line 56 of file mqtt.cpp.
Referenced by mqtt::MqttClient::setup().
onMqttDisconnect()
void mqtt::onMqttDisconnect (AsyncMqttClientDisconnectReason reason)
Definition at line 73 of file mqtt.cpp.
Referenced by mqtt::MqttClient::setup().
onMqttMessage()
void mqtt::onMqttMessage (char * topic, char * payload, AsyncMqttClientMessageProperties properties, size_t len, size_t index, size_t total)
Definition at line 95 of file mqtt.cpp.
Referenced by mqtt::MqttClient::setup().
onMqttPublish()
void mqtt::onMqttPublish (uint16_t packetId)
Definition at line 132 of file mqtt.cpp.
Referenced by mqtt::MqttClient::setup().
onMqttSubscribe()
void mqtt::onMqttSubscribe (uint16_t packetId, uint8_t qos)
Definition at line 81 of file mqtt.cpp.
Referenced by mqtt::MqttClient::setup().
onMqttUnsubscribe()
void mqtt::onMqttUnsubscribe (uint16_t packetId)
Definition at line 89 of file mqtt.cpp.
Referenced by mqtt::MqttClient::setup().
WiFiEvent() [1/2]
void mqtt::WiFiEvent (arduino_event_id_t event)
Definition at line 35 of file mqtt.cpp.
Referenced by mqtt::MqttClient::setup().
WiFiEvent() [2/2]
void mqtt::WiFiEvent (WiFiEvent_t event)
Variable Documentation
mqttClient
AsyncMqttClient mqtt::mqttClient
Definition at line 18 of file mqtt.cpp.
Referenced by connectToMqtt(), onMqttConnect(), and mqtt::MqttClient::setup().
mqttReconnectTimer
TimerHandle_t mqtt::mqttReconnectTimer
Definition at line 19 of file mqtt.cpp.
Referenced by onMqttDisconnect(), mqtt::MqttClient::setup(), and WiFiEvent().